### ISSUE TITLE
Display does not update if no network

### ISSUE THREAD

**Issue by va3wam** [va3wam/TWIPe#76]
If Twipe fails to connect to the WiFi access point he does not update his OLED displays when he is put past 30 degrees. The desired behaviour is to show the MAC address and a message that says no WiFi.

**Comment by nerdoug** [comment]
The code does actually update the OLED display with the current network parameters. Since they're not initialized, they default to null strings, which looks like a failure to display. I've changed the default strings to things like "-no IP address'" where the IP address is normally displayed. This means that the same display is done at setup() and at vertical-30. I'm changing the right OLED to show setup() stage, and then balance state. Also optimizing the OLED display routines which eat a lot of CPU currently.
