### ISSUE TITLE
Motors start up tense

### ISSUE THREAD

**Issue by va3wam** [va3wam/TWIPe#86]
We cannot spin the wheels when the robot first starts up. Once the robot tries to balance and lays back down we can spin the wheels.  We need to change the startup routine to act the same way as the routine when the robot lays back down.

**Comment by nerdoug** [comment]
This has been reduced by disabling motors in setup(). Still takes a while, because network connection happens first, and can be slow. In some ways, keeping motors tense once we've started using them is a good thing, because it keeps the DRV motor controllers synchronized with the state of the stepper coil magnetic stats.
